[theme]
primaryColor             = "#0CC9A8"
backgroundColor          = "#05101E"
secondaryBackgroundColor = "#0A1F3A"
textColor                = "#E4ECF7"
font                     = "sans serif"

[server]
headless = true
enableCORS = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false